import ResetPasswordForm from "@/components/forms/ResetPasswordForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Reset-password",
  description: "Generated by Masud Rana",
};
const ResetPasswordPage = () => {
  return (
    <div>
      <ResetPasswordForm />
    </div>
  );
};

export default ResetPasswordPage;
