import EmailVerifyForm from "@/components/forms/EmailVerifyForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Email-verify",
  description: "Generated by Masud Rana",
};
const EmailVerifyPage = () => {
  return (
    <div>
      <EmailVerifyForm />
    </div>
  );
};

export default EmailVerifyPage;
