import Profile from "@/components/ui/Profile";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by Masud Rana",
};
const ProfilePage = () => {
  return <Profile />;
};

export default ProfilePage;
