import DashboardBooking from '@/components/dashboard/ui/DashboardBooking';
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Booking",
  description: "Generated by Masud Rana",
};
const DashboardBookingPage = () => {
    return (
        <>
           <DashboardBooking /> 
        </>
    );
};

export default DashboardBookingPage;