import FaqAddForm from "@/components/dashboard/forms/FaqAddForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Faq-create",
  description: "Generated by Masud Rana",
};
const FaqCreatePage = () => {
  return (
    <>
      <FaqAddForm />
    </>
  );
};

export default FaqCreatePage;
