import Banner from '@/components/ui/Banner';
import Services from '@/components/ui/Services';
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Service",
  description: "Generated by Masud Rana",
};
const ServicePage = () => {
    const options = [
        {
            label: "Home",
            link: "/",
            active: "home"
        },
        {
            label: "Service",
            link: "#",
            active: ""
        }
    ]
    return (
        <>
            <Banner menu={options} title='Service Page' />
            <Services />
        </>
    );
};

export default ServicePage;