import CategoryEditForm from "@/components/dashboard/forms/CategoryEditForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Category-edit",
  description: "Generated by Masud Rana",
};
const CategoryEditPage = ({ params }: { params: any }) => {
  const { id } = params;
  return <CategoryEditForm id={id} />;
};

export default CategoryEditPage;
