import DashBoardFeedbackDetails from "@/components/dashboard/ui/DashBoardFeedbackDetails";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Feedback-details",
  description: "Generated by Masud Rana",
};
const FeedbackDetailsPage = ({ params }: { params: any }) => {
  const { id } = params;
  return (
    <>
      <DashBoardFeedbackDetails id={id} />
    </>
  );
};

export default FeedbackDetailsPage;
