import ServiceAddForm from "@/components/dashboard/forms/ServiceAddForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Service-create",
  description: "Generated by Masud Rana",
};
const ServiceCreatePage = () => {
  return (
    <>
      <ServiceAddForm />
    </>
  );
};

export default ServiceCreatePage;
