import Banner from "@/components/ui/Banner";
import ServiceDetails from "@/components/ui/ServiceDetails";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Service-details",
  description: "Generated by Masud Rana",
};
const ServiceDetailsPage = ({params}: {params: any}) => {
    const {id} = params;
    const options = [
        {
          label: "Home",
          link: "/",
          active: "home"
        },
        {
          label: "Service",
          link: "/service",
          active: "service"

        },
        {
          label: "Service Details",
          link: "#",
          active: ""
        },
      ];
    return (
        <>
        <Banner menu={options} title="Service Details Page"/>
        <ServiceDetails id={id} />
        </>
    );
};

export default ServiceDetailsPage;