import Accordion from "@/components/ui/Accordion";
import Banner from "@/components/ui/Banner";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Faq",
  description: "Generated by Masud Rana",
};
const FaqPage = () => {
  const options = [
    {
      label: "Home",
      link: "/",
      active: "home"
    },
    {
      label: "Faq",
      link: "#",
      active: ""
    },
  ];
  return (
    <>
      <Banner menu={options} title="Faq Page" />
      <Accordion />
    </>
  );
};

export default FaqPage;
