import Carts from "@/components/ui/Carts";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Carts",
  description: "Generated by Masud Rana",
};
const CartsPage = () => {
  return <Carts />;
};

export default CartsPage;
