import ResetPasswordForm from "@/components/forms/ResetPasswordForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Reset-password",
  description: "Generated by Masud Rana",
};
const ResetPasswordPage = ({ params }: any) => {
  const { id, token } = params;
  console.log({ id, token });

  return (
    <div>
      <ResetPasswordForm id={id} token={token} />
    </div>
  );
};

export default ResetPasswordPage;
