import DashboardFeedback from "@/components/dashboard/ui/DashBoardFeedback";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard-feedback",
  description: "Generated by Masud Rana",
};

const DashboardFeedbackPage = () => {
  return (
    <>
      <DashboardFeedback />
    </>
  );
};

export default DashboardFeedbackPage;
