import DashboardCategory from '@/components/dashboard/ui/DashBoardCategory';
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboar-Category",
  description: "Generated by Masud Rana",
};
const CategoryPage = () => {
    return (
        <DashboardCategory />
    );
};

export default CategoryPage;