import CreateAdminForm from "@/components/dashboard/forms/CreateAdminForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Admin-create",
  description: "Generated by Masud Rana",
};
const CreateAdminPage = () => {
  return <CreateAdminForm />;
};

export default CreateAdminPage;
