import ProfileEditForm from "@/components/forms/ProfileEditForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Profile-update",
  description: "Generated by Masud Rana",
};
const ProfileUpdatePage = ({params}: {params: any}) => {
    const {id} = params;
    return (
        <ProfileEditForm id={id} />
    );
};

export default ProfileUpdatePage;