import FaqEditForm from "@/components/dashboard/forms/FaqEditForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Faq-edit",
  description: "Generated by Masud Rana",
};

const FaqEditPage = ({ params }: { params: any }) => {
  const { id } = params;
  return (
    <>
      <FaqEditForm id={id} />
    </>
  );
};

export default FaqEditPage;
