import CategoryAddForm from "@/components/dashboard/forms/CategoryAddForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Category-create",
  description: "Generated by Masud Rana",
};
const CategoryCreatePage = () => {
  return <CategoryAddForm />;
};

export default CategoryCreatePage;
