import DashboardService from "@/components/dashboard/ui/DashboardService";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dahboard-service",
  description: "Generated by Masud Rana",
};
const ServicePage = () => {
  return (
    <>
      <DashboardService />
    </>
  );
};

export default ServicePage;
