import ContactForm from '@/components/forms/ContactForm';
import Banner from '@/components/ui/Banner';
import ContactCards from '@/components/ui/ContactCards';
import MapContainer from '@/components/ui/MapContainer';

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by Masud Rana",
};
const ContactPage = () => {
    const options = [
        {
            label: "Home",
            link: "/",
            active: "home"
        },
        {
            label: "Contact",
            link: "#",
            active: ""
        }
    ]

    return (
        <>
            <Banner menu={options} title='Contact Page' />
            <ContactCards />
            <ContactForm />
            <MapContainer />
        </>
    );
};

export default ContactPage;