import BookingForm from "@/components/forms/BookingForm";
import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Booking",
  description: "Generated by Masud Rana",
};
const BookingPage = ({ params }: { params: any }) => {
  const { id } = params;
  return (
    <>
      <BookingForm serviceId={id} />
    </>
  );
};

export default BookingPage;
